ARG PLATFORM
ARG ROS_DIST
#FROM --platform=linux/$PLATFORM ros:$ROS_DIST-ros-core-stretch
FROM --platform=linux/$PLATFORM ros:$ROS_DIST-ros-core

ARG ROS_DIST

RUN mkdir /src && \
    echo "" > /src/ros-entery.sh && \
    chmod +x /src/ros-entery.sh

COPY ./ros-entery.sh /src/ros-entery.sh

RUN mkdir /data && \
    apt-get update && \
    export CHOOSE_ROS_DISTRO=${ROS_DIST} && \
    apt-get install -y \
    ros-${CHOOSE_ROS_DISTRO}-rosbridge-server \
    ros-${CHOOSE_ROS_DISTRO}-tf2-web-republisher \
    python-cffi python-bson python-twisted \
    python-rosdep python-rosinstall python-rosinstall-generator python-wstool \
    python-pip \
    libssl-dev libffi-dev \
    python-autobahn && \ 
    #python-dev && \
    #---- It is important to install bson befor pymongo
    pip install twisted bson cffi && \
    pip install tornado pyOpenSSL && \
    pip install pymongo && \
    pip install autobahn
    /bin/bash -c "source /opt/ros/${CHOOSE_ROS_DISTRO}/setup.bash; sudo rosdep init; rosdep update; " && \
    /bin/bash -c "source /opt/ros/${CHOOSE_ROS_DISTRO}/setup.bash; rosdep install -y rosbridge_server; "


#EXPOSE 9090

#CMD [ "/bin/bash", "-c", "'source /opt/ros/${CHOOSE_ROS_DISTRO}/setup.bash; /src/ros-entery.sh;'" ]
CMD bash -C '/src/ros-entery.sh';'bash'
