version: '3'
services:
  roscore_build:
    image: "sausy/roscore:${ARCHITECTUR}_${ROSVERSION}"
    build:
      context: .
      args:
        ROS_DIST: ${ROSVERSION}
        PLATFORM: ${ARCHITECTUR}
      dockerfile: Dockerfile-roscore
  roscore:
    image: "sausy/roscore:${ARCHITECTUR}_${ROSVERSION}"
    container_name: roscore
    hostname: roscore
    network_mode: "host"
    environment:
      - ROS_MASTER_URI=http://localhost:11311
