ARG PLATFORM
ARG ROS_DIST
#FROM --platform=linux/$PLATFORM ros:$ROS_DIST-ros-core-stretch
FROM --platform=linux/$PLATFORM ros:$ROS_DIST-ros-base

ARG ROS_DIST

#COPY ./ros-entry.sh /ros-entry.sh
#CMD bash -C '/ros-entry.sh';'bash'

ENTRYPOINT ["/bin/bash", "-c", "source /rvizweb_ws/install/setup.bash && /bin/bash"]

RUN mkdir /rvizweb_ws && \
    apt-get update && \
    apt-get install -y python-rosdep || apt-get install -y python3-rosdep && \
    apt-get install -y curl git && \
    # init rosdep && \
    /bin/bash -c "source /opt/ros/${ROS_DIST}/setup.bash; sudo rosdep init; rosdep update; " && \
    # Basic tools and dependencies and nodejs LTS PPA. && \
    apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
    # install webrviz from git  && \
    git clone https://github.com/osrf/rvizweb/ rvizweb_ws/src/rvizweb -b master 
RUN cd /rvizweb_ws && \
    ls -al && \
    rosdep install --from-paths src --ignore-src -r -y && \
    /bin/bash -c "source /opt/ros/${ROS_DIST}/setup.bash; catkin_make install;"
